# Generated by Django 5.0.6 on 2024-05-17 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_orderitems_order_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerAdderss',
            new_name='CustomerAddress',
        ),
    ]
